name: KD Linter

on:
  push:
    branches:
      - '**'

jobs:
  lint:
    name: Lint KD Files
    runs-on: ubuntu-latest
    if: false
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Build KD Linter
        run: |
          go build -o kdlinter .

      - name: Run KD Linter
        run: |
          ./kdlinter .